# Generated by Django 4.2.3 on 2023-08-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteca',
            name='instalado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carrito',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lista_amigos',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
